[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    moononournation/GFX Library for Arduino @ ^1.4.9
    lvgl/lvgl @ ^9.2.0
    lewisxhe/SensorLib @ ^0.2.1
    links2004/WebSockets @ ^2.6.1
    bblanchon/ArduinoJson @ ^7.2.0

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -I./include
    -I./assets
    -I./backgrounds
    -D XPOWERS_CHIP_AXP2101

build_src_filter = +<main.cpp> +<es8311.c> +<../assets/*.c> +<../backgrounds/*.c>
